--05.
CREATE DATABASE Online_Store;
CREATE TABLE OrderItems(
   OrderID INT NOT NULL,
   ItemID INT NOT NULL
);
CREATE TABLE Orders(
   OrderID INT PRIMARY KEY NOT NULL,
   CustomerID INT NOT NULL
);
CREATE TABLE Items(
   ItemID INT PRIMARY KEY NOT NULL,
   [Name] NVARCHAR(100) NOT NULL,
   ItemTypeID INT NOT NULL
);
CREATE TABLE Customers(
   CustomerID INT PRIMARY KEY NOT NULL,
   [Name] NVARCHAR(100) NOT NULL,
   Birthday DATE NULL,
   CityID INT NOT NULL
);
CREATE TABLE Cities(
   CityID INT PRIMARY KEY NOT NULL,
   [Name] NVARCHAR(100) NOT NULL
);
CREATE TABLE ItemTypes(
   ItemTypeID INT PRIMARY KEY NOT NULL,
   [Name] NVARCHAR(100) NOT NULL
);
ALTER TABLE OrderItems
ADD
CONSTRAINT PK_IDS
PRIMARY KEY(OrderID,ItemID);
ALTER TABLE OrderItems
ADD 
CONSTRAINT FK_OrderID
FOREIGN KEY(OrderID)
REFERENCES Orders(OrderID);
ALTER TABLE OrderItems
ADD 
CONSTRAINT FK_ItemID
FOREIGN KEY(ItemID)
REFERENCES Items(ItemID);
ALTER TABLE Orders
ADD 
CONSTRAINT FK_CustomerID
FOREIGN KEY(CustomerID)
REFERENCES Customers(CustomerID);
ALTER TABLE Customers
ADD 
CONSTRAINT FK_CityID
FOREIGN KEY(CityID)
REFERENCES Cities(CityID);
ALTER TABLE Items
ADD 
CONSTRAINT FK_ItemTypeID
FOREIGN KEY(ItemTypeID)
REFERENCES ItemTypes(ItemTypeID);